sudo: true
language: julia
addons:
    apt:
        update: true
julia:
      - 1
after_success:
      - julia -e 'using Pkg;cd(Pkg.dir("HMMSpikeSorter")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
