language: julia
addons:
    apt:
        update: true
julia:
      - release
after_success:
      - julia -e 'cd(Pkg.dir("HMMSpikeSorter")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
